name: Latest dev.to post workflow
on:
 schedule: # Run workflow automatically
   # This will make it run every hour
   - cron: '10 1 * * *' 
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest blog posts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
         comment_tag_name: "DEV-TO-POST-LIST"
         commit_message: "Updated readme with the latest dev.to posts"
         feed_list: "https://dev.to/feed/mainick"
         max_post_count: 10
