name: Latest medium stories workflow
on:
  schedule: # Run workflow automatically
    # This will make it run every hour
    - cron: '0 1 * * *' 
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch: 
jobs:
  update-readme-with-medium-stories:
    name: Update this repo's README with latest mediume stories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM-STORIES"
          commit_message: "Updated readme with the latest medium stories"
          feed_list: "https://medium.com/feed/@mainick"
          max_post_count: 10